name: iconflow
channels:
  - pytorch
  - conda-forge
dependencies:
  - cudatoolkit=11.3
  - pillow>=9.1.0
  - pip>=22.0.4
  - python=3.9
  - pytorch==1.11.0
  - torchinfo==1.7.1
  - torchvision==0.12.0
  - torchdiffeq==0.2.2
  - pip:
    - fire==0.4.0
    - scikit-image==0.19.3
    - opencv-python-headless==4.5.5.64
    - tensorboard==2.5.0
    - protobuf==3.20.*
    - pytorch_lightning
